[package]
name = "SELinuxhll"
version = "0.0.1"
authors = ["Daniel Burgener <Daniel.Burgener@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "libhll"
path = "src/lib/lib.rs"

[[bin]]
name = "hllc"
path = "src/hllc.rs"

[[bin]]
name = "audit2hll"
path = "src/audit2hll.rs"
