[package]
name = "SELinuxhll"
version = "0.0.1"
authors = ["Daniel Burgener <Daniel.Burgener@microsoft.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.5"

[dependencies]
lalrpop-util = "0.19.5"
regex = "1"
sexp = "1.1.4"
