[package]
name = "selinuxhll"
version = "0.0.1"
authors = ["Daniel Burgener <Daniel.Burgener@microsoft.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
codespan-reporting = "0.11"
lalrpop-util = "0.19"
regex = "1"
sexp = "1.1"
thiserror = "1.0"
